Plugin version @PLUGIN_VERSION@

Revised on August 04, 2022














== Plugin configurations

Plugin configurations are sets of parameters that apply
across some or all of the plugin procedures. They
reduce repetition of common values, create
predefined parameter sets for end users, and
securely store credentials where needed. Each configuration
is given a unique name that is entered in designated
parameters on procedures that use them.


=== Creating plugin configurations

To create plugin configurations in {CD}, do these steps:

* Go to menu:Administration[Plugins] to open the Plugin Manager.
* Find the @PLUGIN_NAME@ row.
* Click *Configure* to open the
     Configurations page.
* Click *Create Configuration* as per the description of parameters below.


For communicating with Docker host, you need

. Docker endpoint (For example, tcp://swarmmanager.example.com:2376)
. TLS certificates in case of cert based authentication with Docker endpoint.



=== Configuration procedure parameters

[cols=",",options="header"]
|===
|Parameter |Description

|__**Configuration:**__ | Unique name for the plugin configuration.


|Description: | Description for the plugin configuration.


|Docker Registry: | Custom Docker Registry (i.e., myregistry.local or localhost:5000). Leave empty for default Registry which is Docker Hub.


|Username and password | Username and password for Docker Registry (Docker Hub or private Docker Registry).


|Debug Level | This option sets debug level for logs. If info is selected, only summary information will be shown, for debug, there will be some debug information and for trace the whole requests and responses will be shown.


|===





[[procedures]]
== Plugin procedures




[[runDockerBuild]]
=== runDockerBuild


Performs a docker build



==== runDockerBuild parameters
[cols=",",options="header"]
|===
|Parameter |Description

| __**Configuration Name**__ | Previously defined configuration for the plugin


| Use sudo: | Use sudo for running docker build


| __**Build path:**__ | Path to source code


|===






[[runDockerPull]]
=== runDockerPull


Performs a docker pull on the requested image



==== runDockerPull parameters
[cols=",",options="header"]
|===
|Parameter |Description

| __**Configuration Name**__ | Previously defined configuration for the plugin


| Use sudo: | Use sudo for running docker pull


| __**Image name:**__ | Image to pull from Docker Hub


| Image tag: | Tag of image


|===






[[runDockerRun]]
=== runDockerRun


Performs a docker run



==== runDockerRun parameters
[cols=",",options="header"]
|===
|Parameter |Description

| __**Configuration Name**__ | Previously defined configuration for the plugin


| Use sudo: | Use sudo for running docker run


| __**Image name:**__ | Image to run a container from


| Container name: | Assign a name to the container


| Detached mode (-d): | Detached mode: run the container in the background and print the new container ID


| Entrypoint: | Overwrite the default ENTRYPOINT of the image


| Container working directory: | Working directory inside the container


| Publish ports: | Publish a container's port to the host (format: ip:hostPort:containerPort \| ip::containerPort \| hostPort:containerPort \| containerPort). Note: use spaces to delimit port mappings, for example "2666:1666 8088:8080"


| Publish all ports: | Publish all exposed ports to the host interfaces


| Privileged: | Give extended privileges to this container


| Link: | Add link to another container in the form of name:alias


| Command with args: | Command to run within container


|===

















== Known issues
Backslashes (\) are not supported in `.dockerignore` for Artifact2Image procedure. Use forward slashes.




[[rns]]
== Release notes


=== EC-Docker 2.0.0

- Revised EC-Docker plugin to drop the old microservices model and adopt pure Docker procedures with authorization handling.


=== EC-Docker 1.6.5

- Upgraded third-party dependencies to address security issues.


=== EC-Docker 1.6.4

- Support for "Artifactory Classifier" and "Artifactory Extract" fields was added to the Artifact2Image procedure


=== EC-Docker 1.6.3

- The documentation has been migrated to the main site.


=== EC-Docker 1.6.2

- Upgrading dependecies to address security issues.


=== EC-Docker 1.6.1

- Renaming to "{CD}"


=== EC-Docker 1.6.0

- Provisioning of Binary Dependencies (for example Grape jars) in the agent resource, required by this plugin, is now delivered through a newly introduced mechanism called Plugin Dependency Management. Binary dependencies will now be seamlessly delivered to the agent resource from the Flow Server, any time a new version of a plugin is invoked the first time. Flow Repository set up is no longer required for this plugin.

- Add checking connection while creating/editing a configuration.


=== EC-Docker 1.5.3

- Renaming to "CloudBees".


=== EC-Docker 1.5.2

- Images in the help file have been fixed.


=== EC-Docker 1.5.1

- Configurations can be created by users with "@" sign in a name.


=== EC-Docker 1.5.0

- Plugin promotion time has been improved.


=== EC-Docker 1.4.0

- Previously deprecated _Discover_ procedure has been removed. Use the _Import Microservices_ procedure to create microservice models based on the given Docker Compose file contents.

- Fixed the report link for unsupported tags that were not processed by the _Import Microservices_.

- Configured the plugin to allow the ElectricFlow UI to create configs inline of procedure form.


=== EC-Docker 1.3.0

- Added _Import Microservices_ procedure which can be used through the _Import Docker Compose file_ catalog item in the _Containers_ service catalog for creating microservice models in ElectricFlow.

- Added _Artifact2Image_ procedure.

- Discover procedure is _Deprecated_. Use the _Import Microservices_ procedure to create microservice models based on the given Docker Compose file contents

- Added support for retrieving and creating the plugin configurations through the _Configurations_ option on the application process step and the pipeline stage task editors.


=== EC-Docker 1.2.2

- Registered the _Undeploy Service_ procedure as an _Undeploy Service_ operation to enable undeploying micro-services modeled in ElectricFlow from Docker using the service process.

- Added _Create Ingress_ and _Delete Network_ procedures.

- Added support for container update on standalone docker engine.

- Added support for attaching additional networks during container update.


=== EC-Docker 1.2.1

- Added support for Docker network creation.

  * For Stand-alone Docker instances, _Deploy Service_ procedure creates a user defined bridge network if network name given in service mapping page. Procedure uses this network to deploy containers.
  * For Docker Swarm instances, _Deploy Service_ procedure creates a user defined overlay network if network name given in service mapping page. Procedure uses this network to deploy Docker Swarm services.



=== EC-Docker 1.2.0

- Added support for deploying micro-services modeled in ElectricFlow to Docker. Deploying micro-services to the following Docker environments are supported:

  * Stand-alone Docker instances
  * Docker Swarm
  * Docker Enterprise Edition
  * Windows Docker containers on Windows 2016
  * Docker Swarm
  * Docker Enterprise Edition
  * Windows Docker containers on Windows 2016


- Added procedure _Undeploy Service_ to undeploy a previously deployed service.

- Added procedure _Remove Docker Service_ to remove a service running on a stand-alone Docker host or a Docker Swarm cluster.

- Removed support for using EC-Docker as a 'component' plugin. Micro-services based applications should be modeled as applications with services. The services can then be deployed using the native ElectricFlow services deployment capability.


=== EC-Docker 1.0.1

- Discover procedure has been added.


=== EC-Docker 1.0.0

- Introduced the EC-Docker plugin.


