---
pluginInfo:
  pluginName: "EC-Docker"
  version: '2.1.0'
  label: Docker
  description: "Integrates with Docker CLI."
  author: "CloudBees"
  supportLevel: 10
  minCommanderVersion: 10.3
  hasAdoc: true
  supportUrl: "https://cloudbees.com"
  category: "Container Management"
  shell: "cb-perl"
  detailedDescription: 'This plugin allows you to use Docker to build, pull, and run commands.'
properties:
- propertyName: "dockerfiles"
  properties:
  - propertyName: "defaults"
    properties:
    - propertyName: "aspnet"
      value:
        path: "dsl/properties/dockerfiles/defaults/aspnet"
    - propertyName: "csproj"
      value:
        path: "dsl/properties/dockerfiles/defaults/csproj"
    - propertyName: "jetty"
      value:
        path: "dsl/properties/dockerfiles/defaults/jetty"
    - propertyName: "springboot"
      value:
        path: "dsl/properties/dockerfiles/defaults/springboot"
- propertyName: "lib"
  properties:
  - propertyName: "EC"
    properties:
    - propertyName: "PostP"
      value:
        path: "dsl/properties/lib/EC/PostP.pm"
- propertyName: "resources"
  properties:
  - propertyName: "report"
    value:
      path: "dsl/properties/resources/report.html"
- propertyName: "postpLoader"
  value:
    path: "dsl/properties/postpLoader"
procedures:
- name: "runDockerBuild"
  description: "Performs a Docker build."
  hasConfig: true
  parameters:
  - name: "use_sudo"
    type: "checkbox"
    required: false
    adoc: Use sudo for running the Docker build.
    documentation: "Use sudo for running the Docker build."
    label: "Use sudo"
    checkedValue: "1"
    uncheckedValue: "0"
    initiallyChecked: "0"
  - name: "build_path"
    type: "entry"
    required: true
    adoc: Required. The path to the source code.
    documentation: "The path to the source code."
    label: "Build path"
  shell: "cb-perl"
  properties: []
- name: "runDockerPull"
  description: "Performs a Docker pull on the requested image."
  hasConfig: true
  parameters:
  - name: "use_sudo"
    type: "checkbox"
    required: false
    adoc: Use sudo for running the Docker pull.
    documentation: "Use sudo for running the Docker pull."
    label: "Use sudo"
    checkedValue: "1"
    uncheckedValue: "0"
    initiallyChecked: "0"
  - name: "image_name"
    type: "entry"
    required: true
    adoc: Required. The image to pull from Docker Hub.
    documentation: "The image to pull from Docker Hub."
    label: "Image name"
  - name: "tag"
    type: "entry"
    required: false
    adoc: The image tag.
    documentation: "The image tag."
    label: "Image tag"
  shell: "cb-perl"
  properties: []
- name: "runDockerRun"
  description: "Performs a Docker run."
  hasConfig: true
  parameters:
  - name: "use_sudo"
    type: "checkbox"
    required: false
    adoc: Use sudo for running the Docker run.
    documentation: "Use sudo for running the Docker run."
    label: "Use sudo"
    checkedValue: "1"
    uncheckedValue: "0"
    initiallyChecked: "0"
  - name: "image_name"
    type: "entry"
    required: true
    adoc: Required. The image to run a container from.
    documentation: "The image to run a container from."
    label: "Image name"
  - name: "container_name"
    type: "entry"
    required: false
    adoc: Assigns a name to the container.
    documentation: "Assigns a name to the container."
    label: "Container name"
  - name: "detached_mode"
    type: "checkbox"
    required: false
    adoc: Runs the container in the background and prints the new container ID.
    documentation: "Runs the container in the background and prints\
      \ the new container ID."
    label: "Detached mode (-d)"
    checkedValue: "1"
    uncheckedValue: "0"
    initiallyChecked: "0"
  - name: "entrypoint"
    type: "entry"
    required: false
    adoc: Overwrites the default ENTRYPOINT of the image.
    documentation: "Overwrites the default ENTRYPOINT of the image."
    label: "Entrypoint"
  - name: "working_dir"
    type: "entry"
    required: false
    adoc: The working directory inside the container.
    documentation: "The working directory inside the container."
    label: "Container working directory"
  - name: "published_ports"
    type: "entry"
    required: false
    adoc: |
      Publish a container's port to the host using the following format: `ip:hostPort:containerPort \| ip::containerPort \| hostPort:containerPort \| containerPort`.
      
      NOTE: Use spaces to delimit port mappings. For example, `2666:1666 8088:8080`.
    documentation: "Publish a container's port to the host using the following format: ip:hostPort:containerPort\
      \ | ip::containerPort | hostPort:containerPort | containerPort). Note: Use\
      \ spaces to delimit port mappings, for example \"2666:1666 8088:8080\""
    label: "Publish ports"
  - name: "publish_all_ports"
    type: "checkbox"
    required: false
    adoc: Publish all exposed ports to the host interfaces.
    documentation: "Publish all exposed ports to the host interfaces."
    label: "Publish all ports"
    checkedValue: "1"
    uncheckedValue: "0"
    initiallyChecked: "0"
  - name: "privileged"
    type: "checkbox"
    required: false
    adoc: Give extended privileges to this container.
    documentation: "Give extended privileges to this container."
    label: "Privileged"
    checkedValue: "1"
    uncheckedValue: "0"
    initiallyChecked: "0"
  - name: "container_links"
    type: "entry"
    required: false
    adoc: Add a link to another container in the form of `name:alias`.
    documentation: "Add a link to another container in the form of name:alias"
    label: "Link"
  - name: "command_with_args"
    type: "entry"
    required: false
    adoc: The command to run within the container.
    documentation: "Command to run within the container"
    label: "Command with args"
  shell: "cb-perl"
  properties: []
configuration:
  hasDebugLevel: true
  checkConnection: false
  parameters:
  - name: "config"
    type: "entry"
    required: true
    adoc: Required. The unique name for the plugin configuration.
    documentation: "The unique name for the plugin configuration."
    label: "Configuration"
  - name: "desc"
    type: "entry"
    required: false
    adoc: The description for the plugin configuration.
    documentation: "The description for the plugin configuration."
    label: "Description"
  - name: "registry"
    type: "entry"
    required: false
    adoc: The custom Docker Registry. For example, `myregistry.local` or `localhost:5000`. Leave empty to use the default Registry, which is Docker Hub.
    documentation: "The custom Docker Registry. For example, myregistry.local or localhost:5000. Leave empty to use the default Registry, which is Docker Hub."
    label: "Docker Registry"
  - name: credential
    label: Username and password
    type: credential
    required: false
    adoc: The username and password for the Docker Registry (Docker Hub or private Docker Registry).
    documentation: The username and password for the Docker Registry (Docker Hub or private Docker Registry).
