version: '3'
services:
  electric-flow:
    image: "us-east1-docker.pkg.dev/cloudbees-artifact-registry/flow/plugin-specs/electricflow/efserver:latest"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - internal
    container_name: electricflow
    tty: true
    extra_hosts:
      - maven.org:127.0.0.1
      - repo1.maven.org:127.0.0.1
      - jcenter.bintray.com:127.0.0.1

  docker:
    image: "us-east1-docker.pkg.dev/cloudbees-artifact-registry/flow/plugin-specs/electricflow/dind:latest"
    ports:
      - "7808:7808"
    networks:
      - internal
    container_name: docker
    tty: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  internal:
    driver: bridge
