version: '3'
services:
  electric-flow:
    image: "electricflow/efserver:latest"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - internal
    container_name: electricflow
    tty: true
#    volumes:
#      - /home/savva/Downloads/artifacts:/home/ecloud

#  artifactory:
#    image: 'electricflow/artifactory:pro-5.6.2'
#    ports:
#    - "8081:8081"
#    networks:
#    - internal
#    container_name: artifactory
#    tty: true

#  docker:
#    image: "docker:stable-dind"
#    ports:
#      - "2375:2375"
#    networks:
#      - internal
#    container_name: docker
#    tty: true
#    privileged: true

networks:
  internal:
    driver: bridge
