version: '3'
services:
  electric-flow:
    image: "electricflow/efserver:latest"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - internal
    container_name: electricflow
    tty: true
    extra_hosts:
      - maven.org:127.0.0.1
      - repo1.maven.org:127.0.0.1
      - jcenter.bintray.com:127.0.0.1

#Not today
#  docker:
#    image: "docker:stable-dind"
#    ports:
#      - "2375:2375"
#    networks:
#      - internal
#    container_name: docker
#    tty: true
#    privileged: true

networks:
  internal:
    driver: bridge
